# Start the testnet server with the command 'docker-compose up -d'

web-server:
  build: ./production/
  dockerfile: Dockerfile
  container_name: web-server
  ports:
    - "3210:3210"  # <host port>:<container port>
    - "4231:4002"  # IPFS
  volumes:
    - ./ipfs-data:/home/safeuser/ipfs-web-server/ipfs-data
  restart: always

tor:
  image: goldy/tor-hidden-service
  container_name: tor-server
  links:
    - troutsblog
  environment:
      TROUTSBLOG_PORTS: 80:3210 # Map port to detected service
  volumes:
    - ./keys:/var/lib/tor/hidden_service/
  restart: always
